name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: .fvmrc
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: dart analyze
      - run: flutter test
